## Azure ML - Training in PyTorch
* Author: Stephen Haddad
* Affiliation: UK Met Office
* History: 1.0
* Last update: 2026-02-10
* © British Crown Copyright 2017-2065, Met Office. Please see LICENSE.md for license details.

## Overview of the broad topic covered

In this notebook, we demonstrate training a pytorch model in AzureML. This is a variation on the Climate Zones tutorial found elsewhere in this repository.

### Environment 
This notebook uses the environment defined in this repository in the [environments/requirements_pytorch.yaml](../../../environments/requirements_pytorch.yaml) conda file, togther with the AzureML SDK. Use the `azure_conda_setup.sh` script to create a local environment on a compute instance.

### Imports

In [1]:
import pathlib
import os
import datetime
import json

In [2]:
import numpy 
import pandas

In [3]:
import matplotlib
import matplotlib.pyplot

In [4]:
import sklearn
import sklearn.preprocessing
import sklearn.tree

In [5]:
import mlflow

/anaconda/envs/dscop_pytorch/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [6]:
import torch

## COnnect to AzureML workspace
We are going to use various features of AzureML, especially for data access and experiment tracking.

In [8]:
from azure.ai.ml import MLClient
from azure.identity import DefaultAzureCredential

In [9]:

ml_client = MLClient.from_config(credential=DefaultAzureCredential())

Found the config file in: /config.json

## Load and prepare data 
We will now load the dataset and do the usual data prep steps, like train/test split and normalisation.

#### Dataset parameters

In [17]:
with open(pathlib.Path.cwd().parent / 'climate_zones' / 'config.json') as tutorial_config:
    tutorial_config = json.load(tutorial_config)
tutorial_config

{'platform': 'mo_linux',
 'default_dirs': {'mo_linux': '/data/users/dscop/ml_tutorial/',
  'jasmin': '/gws/ssde/j25a/mmh_storage/ai4c_data/'},
 'random_seed': 12345,
 'climate_subgroups': {'non-land': 'None',
  'Af': 'Tropical, rainforest',
  'Am': 'Tropical, monsoon',
  'Aw': 'Tropical, savannah',
  'BWh': 'Arid, desert, hot',
  'BWk': 'Arid, desert, cold',
  'BSh': 'Arid, steppe, hot',
  'BSk': 'Arid, steppe, cold',
  'Csa': 'Temperate, dry summer, hot summer',
  'Csb': 'Temperate, dry summer, warm summer',
  'Csc': 'Temperate, dry summer, cold summer',
  'Cwa': 'Temperate, dry winter, hot summer',
  'Cwb': 'Temperate, dry winter, warm summer',
  'Cwc': 'Temperate, dry winter, cold summer',
  'Cfa': 'Temperate, no dry season, hot summer',
  'Cfb': 'Temperate, no dry season, warm summer',
  'Cfc': 'Temperate, no dry season, cold summer',
  'Dsa': 'Cold, dry summer, hot summer',
  'Dsb': 'Cold, dry summer, warm summer',
  'Dsc': 'Cold, dry summer, cold summer',
  'Dsd': 'Cold, dry summer, very cold winter',
  'Dwa': 'Cold, dry winter, hot summer',
  'Dwb': 'Cold, dry winter, warm summer',
  'Dwc': 'Cold, dry winter, cold summer',
  'Dwd': 'Cold, dry winter, very cold winter',
  'Dfa': 'Cold, no dry season, hot summer',
  'Dfb': 'Cold, no dry season, warm summer',
  'Dfc': 'Cold, no dry season, cold summer',
  'Dfd': ',Cold, no dry season, very cold winter',
  'ET': 'Polar, tundra',
  'EF': 'Polar, frost'},
 'resolutions_names': {'0.1': '0p1', '0.5': '0p5', '1.0': '1p0'},
 'dataset_prefix': {'climate_mean': 'ensemble_mean',
  'climate_std': 'ensemble_std',
  'climate_zone': 'koppen_geiger'},
 'fname_template': '{prefix}_{res}.{suffix}',
 'time_dir_template': '{start_year}_{end_year}',
 'csv_out_template': 'climate_zones_{resolution}.csv',
 'future_scenarios': ['ssp119',
  'ssp126',
  'ssp245',
  'ssp370',
  'ssp434',
  'ssp460',
  'ssp585'],
 'historic_scenarios': ['historic']}

In [18]:
data_asset = ml_client.data.get("climate_zones_1_0", version="1")

In [19]:
data_asset.path

'azureml://subscriptions/9734ed68-621d-47ed-babd-269110dbacb1/resourcegroups/1-da6c1ccf-playground-sandbox/workspaces/dscoptest1/datastores/dscopworkspacestore/paths/climate_zones/climate_zones_1p0.csv'

In [20]:
resolutions_dict = {float(k1): v1 for k1,v1 in tutorial_config['resolutions_names'].items()}

dataset_prefix_dict = tutorial_config['dataset_prefix']

format_str = 'nc'
historic_scenario_str = 'historic'

future_scenario_list = tutorial_config['future_scenarios']
historic_scenario_list = tutorial_config['historic_scenarios']

time_periods = { 
    (1901,1930): historic_scenario_list, 
    (1931,1960): historic_scenario_list,
    (1961,1990): historic_scenario_list,
    (1991,2020): historic_scenario_list,
    (2041,2070): future_scenario_list,
    (2071,2099): future_scenario_list,
}

#### Load data for training

In [21]:
current_res = 1.0

In [22]:
mlready_data_path = df = data_asset.path

In [23]:
zones_df = pandas.read_csv(mlready_data_path)

Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration

We have two options for the target. We have the full 30 class climate subgroups of the Koppen-Geiger classification data from the original dataset. We also have the processed five class climate group target, which presents an easier target for our classification algorithm to predict.

#### Selecting features

In [24]:
predictors_dict = {
    'precip_mean': [c1 for c1 in zones_df.columns if 'precipitation' in c1 and 'mean' in c1],
    'precip_std': [c1 for c1 in zones_df.columns if 'precipitation' in c1 and 'std' in c1],
    'temp_mean': [c1 for c1 in zones_df.columns if 'air_temperature' in c1 and 'mean' in c1],
    'temp_std': [c1 for c1 in zones_df.columns if 'air_temperature' in c1 and 'std' in c1],
}

In [25]:
target_var = 'climate_group' # 5 classes
# target_var = 'climate_subgroup # 30 classes

In [26]:
predictors = predictors_dict['precip_mean'] + predictors_dict['temp_mean']
predictors

['precipitation_1.0_mean',
 'precipitation_2.0_mean',
 'precipitation_3.0_mean',
 'precipitation_4.0_mean',
 'precipitation_5.0_mean',
 'precipitation_6.0_mean',
 'precipitation_7.0_mean',
 'precipitation_8.0_mean',
 'precipitation_9.0_mean',
 'precipitation_10.0_mean',
 'precipitation_11.0_mean',
 'precipitation_12.0_mean',
 'air_temperature_1.0_mean',
 'air_temperature_2.0_mean',
 'air_temperature_3.0_mean',
 'air_temperature_4.0_mean',
 'air_temperature_5.0_mean',
 'air_temperature_6.0_mean',
 'air_temperature_7.0_mean',
 'air_temperature_8.0_mean',
 'air_temperature_9.0_mean',
 'air_temperature_10.0_mean',
 'air_temperature_11.0_mean',
 'air_temperature_12.0_mean']

#### Train/test split

In [27]:
random_seed = tutorial_config['random_seed']

In [28]:
test_frac = 0.1
val_frac = 0.1
val_frac_sub = (val_frac / (1.0-test_frac) )

In [29]:
test_df = zones_df.groupby(['period_start','scenario']).sample(frac=test_frac, random_state=random_seed)
remain_df = zones_df.drop(test_df.index)

In [30]:
val_df = remain_df.groupby(['period_start','scenario']).sample(frac=val_frac_sub, random_state=random_seed)
train_df = remain_df.drop(val_df.index)

## Using PyTorch

From this point in the tutorial, we diverge from what was done in the ml training pipeline tutorial as instead of setting up and training our model in scikit-learn, we're going to use a more sophisticated machine learning library called pytorch. This gives us more more control over how we implement our neural network and gives us much more power to use advanced architectures, losss functions and distributed computing techniques.

When using PyTorch, the main difference is that we will specify the details of the neural network architecture and training loop much more explictly. This means we can customise and optimise these details for the particular problem. Key elements of a PyTorch training pipeline, compared to what was previous described are as follows:
1. **Data Loading and Cleaning** - This is usually done through a PyTorch Dataset class. In addition, you create a Dataset Loader object, which has the responsibility for iterating through the data in the dataset, including shuffling data between epochs where appropriate.</p>
2. **Feature Engineering** - Same as before, but may be a part of the dataset class.</p>
3. **Train/Test split** - Same method as before. Usually different dataset objects will represent the train, validate and test sets.</p>
4. **Data Preparation** - Same as before, but code may be structured differently such that the normalisation and scaling happening inside the PyTorch dataset class.</p>
5. **Algorithm Setup** - Usually you create a class representing the model architecture. You then also specify key hyperparameters such as the optimiser for training the weights, the learning rate, etc. </p>
6. **Algorithm Training** - The elements of the training loop are described more explictly in PyTorch typically with a explicit loop for iterating through batches and an outer loop for iterating through batches.</p>
7. **Inference** - The model object is used as a callable object for producing. </p>
8. **Evaluation** - Evaluation is the same as before. </p>
9. **Interpretability and Explainability** - As model architectures become more complex, it becomes more difficult to explain or interpret the results, this is an active area of research. </p>
10. **Model Storage** - Pytorch has a more sophisticated mechanism for [saving and loading models](https://docs.pytorch.org/tutorials/beginner/saving_loading_models.html). </p>

### Check GPU availability

As a part of this notebook, we will now be training our models using the GPUs on JASMIN. There are some additional steps required for this purpose, such as moving the data and model onto the GPU memory for processing. ML frameworks are especially helpful for this in abtracting away many of the details of this into a few commands.

In this cell, we check whether there is a GPU to use. [CUDA](https://en.wikipedia.org/wiki/CUDA) is the underlying software layer that interfaces to nvidia GPUs. This check allows the notebook to seamlessly work either on a gpu if one is available or to do processing on a cpu when a gpu is not available.

In [31]:
# Autodetect GPU and use if possible
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
device

device(type='cpu')

#### Training hyperparameters

In [32]:
training_params = {
    'batch_size': 16,
    'num_epochs': 2,
    'learning_rate': 0.001,
    'loss': 'CrossEntropyLoss',
    'criterion': 'CrossEntropyLoss',
    'optimizer': 'Adam',
}

### Define a data loader

Pytorch defines the interface between the dataset and machine learning through a base class (`torch.utils.data.Dataset), which follow [pythonic paradigms](https://realpython.com/ref/glossary/pythonic/) for software architecture. The implementation of the class hides away the details of the data being used, so that the dataset can be used in the generic pytorch architecture. There is also then a data loader which is an [iterator](https://www.w3schools.com/python/python_iterators.asp) on the dataset, enabling pytorch to progress through all the data during training. Ultimately the aim of this data architecture is to present the data in the correct [pytorch tensor format](https://docs.pytorch.org/docs/stable/tensors.html) expected by the neural network for training purposes.

#### Key Concepts:
- **Pytorch Dataset**: Handles loading and preparing the data for use with pytorch. Implements key [python built-in methods](), including:</p>
  - [`__init__`](https://docs.python.org/3/reference/datamodel.html#object.__init__) creates the dataset object, and typically loads and transforms the data ready for use, or in a lazy loading paradigm, define the task pipeline for loading the data upon request.
  - [`__len__`](https://docs.python.org/3/reference/datamodel.html#object.__len__) specifies how many data point there are.
  - [`__getitem__`](https://docs.python.org/3/reference/datamodel.html#object.__getitem__) return the item for a particular index.</p>
- [**Pytorch Data Loader**](https://docs.pytorch.org/docs/stable/data.html): Interfaces between the ML algorithm being trained and the dataset, selecting mini batches of data to use with each iteration of the gradient descent with back propogation used for training the neural network. Key parameters include:</p>
  - **dataset** - The dataset to load the data from (as described above).
  - [**batch size**](https://www.geeksforgeeks.org/deep-learning/batch-size-in-neural-network/) - How many samples to use in each mini batch during training.
  - [**shuffle**](https://stats.stackexchange.com/questions/245502/why-should-we-shuffle-data-while-training-a-neural-network) - Whether to shuffle the order of data use during each of the epochs. Data shuffling improves the generalisation of what is learned by the neural network.


Further reading
- [Intro to datasets and data loader - pytorch docs](https://docs.pytorch.org/tutorials/beginner/data_loading_tutorial.html)
- [Tutorial on using CSV data with pytorch data architecture - Machine Learning Mastery](https://machinelearningmastery.com/converting-pandas-dataframes-to-pytorch-dataloaders-for-custom-deep-learning-model-training/)
- [Converting pnadas dataframe to the pytorch](https://www.geeksforgeeks.org/deep-learning/converting-a-pandas-dataframe-to-a-pytorch-tensor/)
- [Encoding target data for a neural network using LabelBinarizer - scikit learn](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelBinarizer.html)

### Implementation details for this tutorial

In [33]:
class ClimateZonesDataset(torch.utils.data.Dataset):
    """
    Inspired by this tutorial:
    https://machinelearningmastery.com/converting-pandas-dataframes-to-pytorch-dataloaders-for-custom-deep-learning-model-training/
    """
    def __init__(self, df_ml, predictor_features, target_feature, device, stats_dict=None):
        self._df_ml = df_ml.reset_index().drop(['index'],axis='columns')
        self._device = device
        self.input_scaler = sklearn.preprocessing.StandardScaler()
        if stats_dict is None:
            self.input_scaler.fit(self._df_ml[predictor_features])
        else:
            self.input_scaler.mean_ = numpy.array(stats_dict['input_mean'])
            self.input_scaler.scale_ = numpy.array(stats_dict['input_scale'])

        self._X = torch.tensor(self.input_scaler.transform(self._df_ml[predictor_features]),  
                               dtype=torch.float32)


        self.target_encoder = sklearn.preprocessing.LabelBinarizer(sparse_output=False)
        if stats_dict is None:
            self.target_encoder.fit(self._df_ml[[target_feature]])
        else:
            self.target_encoder.classes_ = numpy.array(stats_dict['target_classes'],dtype='object')

        
        self._y = torch.tensor(self.target_encoder.transform(self._df_ml[[target_feature]]),
                               dtype=torch.float32)

        self.stats_dict = {
            'input_mean': [float(v1) for v1 in self.input_scaler.mean_],
            'input_scale': [float(v1) for v1 in self.input_scaler.scale_],
            'target_classes': list(self.target_encoder.classes_),
        }
        
    def _repr_html_(self):
        return f'''
        <h1>Climate Zones Dataset</h1>
        Number of samples {len(self._X)}
        '''
    
    def __len__(self):
        return len(self._X)

    def __getitem__(self,idx):
        return self._X[idx], self._y[idx]

We now intialise the validate and test set data loaders. Note that we initialise the preprocessing objects with the values learned from the training data, rather than calculating them on the validate or test data.

### Using our dataset class
Once we have defined the class, we can now initialise objects from it. A typical pattern is to define separate objects for the train, validate and test sets. You then define an iterator, i.e. a data loader object, for each of the dataset objects. Data loaders are a generic class defined by PyTorch that should work with any dataset that complies with the standard interface.

In [34]:
cz_train_ds = ClimateZonesDataset(train_df, predictors, target_var, device)
cz_train_ds

In [35]:
cz_val_ds = ClimateZonesDataset(val_df, predictors, target_var, device, cz_train_ds.stats_dict)
cz_test_ds = ClimateZonesDataset(test_df, predictors, target_var, device, cz_train_ds.stats_dict)

/anaconda/envs/dscop_pytorch/lib/python3.12/site-packages/sklearn/utils/validation.py:2684: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(
/anaconda/envs/dscop_pytorch/lib/python3.12/site-packages/sklearn/utils/validation.py:2684: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(

In [36]:
len(cz_train_ds)

325206

In [37]:
cz_val_ds[1234]

(tensor([-0.5431, -0.5180, -0.4127, -0.3780, -0.4759, -0.5458, -0.5103, -0.4938,
         -0.5388, -0.5015, -0.5389, -0.5469, -0.5396, -0.7533, -0.9728, -1.0988,
         -1.2024, -1.2934, -1.3218, -1.3201, -1.2447, -1.1500, -0.9019, -0.6197]),
 tensor([0., 0., 0., 0., 1.]))

In [38]:
cz_val_ds[1234][0]

tensor([-0.5431, -0.5180, -0.4127, -0.3780, -0.4759, -0.5458, -0.5103, -0.4938,
        -0.5388, -0.5015, -0.5389, -0.5469, -0.5396, -0.7533, -0.9728, -1.0988,
        -1.2024, -1.2934, -1.3218, -1.3201, -1.2447, -1.1500, -0.9019, -0.6197])

In [39]:
cz_val_ds[1234][0].shape

torch.Size([24])

In [40]:
cz_val_ds[1234][1]

tensor([0., 0., 0., 0., 1.])

In [41]:
cz_val_ds[1234][1].shape

torch.Size([5])

In [42]:
cz_train_loader = torch.utils.data.DataLoader(
        cz_train_ds, batch_size=training_params['batch_size'], shuffle=True, num_workers=1,
    )
cz_val_loader = torch.utils.data.DataLoader(
        cz_val_ds, batch_size=training_params['batch_size'], shuffle=False, num_workers=1,
    )

In [43]:
training_params['batch_size']

16

In [44]:
count = 0
for X1,y1 in cz_train_loader:
    print(X1, y1)
    count +=1
    if count > 5:
        break

Exception ignored in: <function PeriodicExportingMetricReader.__init__.<locals>.<lambda> at 0x740c27d22d40>
Traceback (most recent call last):
  File "/anaconda/envs/dscop_pytorch/lib/python3.12/site-packages/opentelemetry/sdk/metrics/_internal/export/__init__.py", line 535, in <lambda>
    after_in_child=lambda: weak_at_fork()()  # pylint: disable=unnecessary-lambda
                           ^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable

tensor([[-0.1645, -0.2294, -0.2181, -0.0487,  0.0351,  0.3103,  0.1461,  0.2793,
          0.1426,  0.1837,  0.0162, -0.1511, -0.6712, -0.4738, -0.0609,  0.1014,
          0.2748,  0.4694,  0.5495,  0.4394,  0.3160,  0.0970, -0.3120, -0.6072],
        [-0.5727, -0.5729, -0.5796, -0.5782, -0.6083, -0.6142, -0.6318, -0.6705,
         -0.6582, -0.6390, -0.6281, -0.6078, -0.2396, -0.5042, -0.7767, -0.9431,
         -1.0454, -1.1322, -1.1814, -1.1710, -1.0908, -0.9519, -0.6417, -0.3217],
        [ 0.0628, -0.1159, -0.1524, -0.0827,  0.0985,  0.2200,  0.1475,  0.1763,
          0.1779,  0.3766,  0.2506,  0.1396, -0.1845, -0.0642,  0.1401,  0.3075,
          0.4451,  0.5296,  0.5825,  0.4932,  0.3962,  0.2583,  0.0610, -0.0959],
        [-0.1408, -0.0768,  0.1052,  0.1659,  0.0967, -0.1764, -0.1756, -0.1530,
         -0.0501, -0.0171, -0.1084, -0.1237, -0.1723, -0.3576, -0.5855, -0.7598,
         -0.8928, -1.0032, -1.0471, -1.0323, -0.9369, -0.8126, -0.5520, -0.2527],
        [ 0.2538,  0.3105,  0.3548,  0.7828,  0.6758,  0.4243,  0.2473,  0.1894,
          0.4259,  0.3805,  0.5997,  0.3525,  0.2349,  0.3094,  0.4221,  0.5435,
          0.6596,  0.7510,  0.7808,  0.7830,  0.7604,  0.6520,  0.5178,  0.3496],
        [ 0.7178,  0.6121,  0.7775,  0.4030, -0.3118, -0.4840, -0.5450, -0.5016,
         -0.1985,  0.5872,  0.6919,  0.6679,  1.4776,  1.3224,  1.0742,  0.7725,
          0.4937,  0.2738,  0.2087,  0.3132,  0.5024,  0.7669,  1.1222,  1.4037],
        [-0.4569, -0.5143, -0.4571,  0.0474,  1.6232,  2.5526,  3.0832,  3.4655,
          2.6899,  1.7568,  0.3163, -0.3419,  1.1501,  1.1896,  1.1967,  1.1504,
          1.0067,  0.8628,  0.7829,  0.8037,  0.9034,  1.0383,  1.1656,  1.1590],
        [ 0.1186, -0.0703, -0.0760, -0.0400,  0.1396,  0.3519,  0.2682,  0.2266,
          0.1779,  0.2821,  0.3290,  0.1714, -0.2274, -0.0919,  0.1794,  0.3740,
          0.5225,  0.5963,  0.6156,  0.5429,  0.4287,  0.2828,  0.0118, -0.2056],
        [-0.3673, -0.4175, -0.4828, -0.4218, -0.0973,  0.0385,  0.1251,  0.2072,
          0.0060, -0.1926, -0.2770, -0.3728, -1.1426, -0.8308, -0.3354,  0.0716,
          0.3323,  0.5296,  0.5763,  0.4808,  0.2705, -0.0473, -0.7053, -1.1876],
        [ 0.1617, -0.0293, -0.0059,  0.1834,  0.4510,  0.5374,  0.6138,  0.4226,
          0.8593,  0.7314,  0.4928,  0.2032, -0.4386, -0.3022, -0.0094,  0.2113,
          0.4229,  0.5232,  0.5660,  0.5450,  0.4699,  0.3072,  0.0725, -0.2621],
        [ 3.3197,  3.2678,  2.1303, -0.0652, -0.6670, -0.6997, -0.7207, -0.7735,
         -0.7541, -0.5454,  0.9351,  3.0472,  1.4317,  1.3612,  1.2139,  1.0451,
          0.8674,  0.6822,  0.6197,  0.7230,  0.9403,  1.2143,  1.4374,  1.4633],
        [-0.5963, -0.6074, -0.6365, -0.6675, -0.6568, -0.6801, -0.6968, -0.7286,
         -0.7469, -0.7501, -0.6762, -0.6255, -0.8886, -1.1657, -1.4484, -1.6279,
         -1.7088, -1.7599, -1.7783, -1.7672, -1.7584, -1.6267, -1.2865, -0.9366],
        [-0.2913, -0.4435, -0.4810, -0.5189, -0.6372, -0.7021, -0.7214, -0.7766,
         -0.7768, -0.7052, -0.3672, -0.3180,  0.9420,  1.0207,  1.1036,  1.1688,
          1.2765,  1.3035,  1.2827,  1.3005,  1.2979,  1.2779,  1.1309,  0.9613],
        [-0.5017, -0.5254, -0.5237, -0.5238, -0.4731, -0.3831, -0.1662, -0.0112,
         -0.2809, -0.2471, -0.3467, -0.4161, -1.2039, -1.0578, -0.9066, -0.6453,
         -0.2847, -0.0680,  0.0042, -0.0160, -0.1544, -0.4507, -0.7487, -1.0746],
        [-0.5389, -0.5469, -0.4935, -0.4956, -0.4134, -0.5817, -0.5971, -0.5969,
         -0.5985, -0.6516, -0.6026, -0.5857, -0.5610, -0.7672, -0.9557, -1.1492,
         -1.2444, -1.3214, -1.3466, -1.3428, -1.3227, -1.1793, -0.9164, -0.6417],
        [-0.5980, -0.6102, -0.6294, -0.6287, -0.6969, -0.6769, -0.7040, -0.6798,
         -0.7578, -0.7355, -0.6860, -0.6246, -0.7845, -1.0384, -1.2866, -1.4515,
         -1.5562, -1.5815, -1.5986, -1.5829, -1.5525, -1.4483, -1.1622, -0.8362]]) tensor([[0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0.],
        [1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 1.]])
tensor([[ 1.8029e-01,  2.2828e-02, -4.9378e-02, -2.2508e-02,  1.5263e-01,
          3.1523e-01,  1.5403e-01,  8.4070e-02,  5.7557e-02,  3.3376e-01,
          2.7998e-01,  2.5005e-01,  3.2820e-02,  1.2124e-01,  2.8478e-01,
          4.6559e-01,  5.7553e-01,  6.2205e-01,  6.6926e-01,  6.0295e-01,
          5.0242e-01,  3.7079e-01,  2.0266e-01,  1.0492e-01],
        [-5.5238e-01, -4.9101e-01, -4.2420e-01, -3.9941e-01, -4.8241e-01,
         -5.5724e-01, -5.1681e-01, -4.9771e-01, -5.9850e-01, -5.6489e-01,
         -5.9574e-01, -5.8131e-01, -7.4163e-01, -9.2770e-01, -1.1297e+00,
         -1.2362e+00, -1.3284e+00, -1.3988e+00, -1.4313e+00, -1.4443e+00,
         -1.4029e+00, -1.2967e+00, -1.0812e+00, -8.2679e-01],
        [ 9.5100e-01,  1.0021e+00,  1.6311e+00,  2.0019e+00,  8.5481e-01,
         -5.4259e-01, -6.5778e-01, -4.9461e-01,  1.4521e-03,  8.7471e-01,
          1.8363e+00,  1.3032e+00,  1.3766e+00,  1.3196e+00,  1.1600e+00,
          1.0107e+00,  8.8732e-01,  7.7898e-01,  7.1677e-01,  7.5820e-01,
          8.7308e-01,  1.0260e+00,  1.2147e+00,  1.3378e+00],
        [-4.9914e-01, -5.2638e-01, -5.5388e-01, -4.7421e-01, -1.9986e-01,
          6.4556e-02,  2.2849e-01,  6.7028e-02,  3.2219e-02, -1.7015e-01,
         -3.7509e-01, -5.1063e-01, -1.4304e+00, -1.0910e+00, -4.5066e-01,
          4.1852e-02,  3.5882e-01,  5.8120e-01,  6.3208e-01,  5.2222e-01,
          2.9433e-01, -1.3532e-01, -9.2507e-01, -1.4793e+00],
        [-3.9942e-01, -4.3236e-01, -4.2420e-01, -3.8290e-01, -6.6425e-01,
         -7.0211e-01, -7.2139e-01, -7.7272e-01, -7.7768e-01, -7.5203e-01,
         -4.8198e-01, -4.5762e-01,  1.1256e+00,  1.1730e+00,  1.2114e+00,
          1.2673e+00,  1.3340e+00,  1.3250e+00,  1.2930e+00,  1.3088e+00,
          1.3304e+00,  1.3683e+00,  1.3275e+00,  1.1966e+00],
        [ 3.2065e+00,  2.7549e+00,  1.5885e+00,  5.3022e-01, -3.3507e-01,
         -5.8654e-01, -6.9898e-01, -7.0067e-01, -6.2203e-01,  1.1738e-01,
          1.6401e+00,  2.8289e+00,  7.7972e-01,  7.9102e-01,  7.4076e-01,
          6.5799e-01,  6.2196e-01,  6.0055e-01,  6.2382e-01,  6.6505e-01,
          7.3435e-01,  7.8887e-01,  7.9254e-01,  7.5430e-01],
        [-4.7802e-01, -5.5431e-01, -1.8172e-01,  7.7113e-01, -1.3085e-01,
         -5.0190e-01, -5.2549e-01, -6.4644e-01, -5.6140e-01, -4.4412e-02,
          8.4483e-01, -3.5128e-03,  1.6582e+00,  1.5964e+00,  1.4321e+00,
          1.2192e+00,  1.0266e+00,  8.6927e-01,  7.8699e-01,  8.1822e-01,
          9.5112e-01,  1.1801e+00,  1.4374e+00,  1.6076e+00],
        [-6.0224e-01, -6.0364e-01, -6.5514e-01, -6.7723e-01, -7.2580e-01,
         -6.9316e-01, -6.9898e-01, -6.9525e-01, -6.6366e-01, -7.1986e-01,
         -6.8007e-01, -6.2107e-01,  1.2328e+00,  1.3252e+00,  1.3512e+00,
          1.3406e+00,  1.3274e+00,  1.3444e+00,  1.3571e+00,  1.3564e+00,
          1.3890e+00,  1.4270e+00,  1.3998e+00,  1.2751e+00],
        [-2.8872e-01, -3.7186e-01, -2.5367e-01, -2.6050e-01,  2.0765e-01,
          5.3253e-01,  1.1427e-01, -3.2130e-02, -6.9131e-02, -1.7209e-01,
         -3.3390e-01, -3.0390e-01, -4.3246e-01, -2.5239e-01,  5.1892e-02,
          2.9380e-01,  4.4064e-01,  5.4251e-01,  6.0110e-01,  5.9674e-01,
          4.9375e-01,  3.0477e-01,  8.9204e-03, -3.2486e-01],
        [-5.5238e-01, -5.5710e-01, -5.7253e-01, -5.9078e-01, -6.0550e-01,
         -6.2317e-01, -6.4187e-01, -6.8828e-01, -6.6456e-01, -6.4676e-01,
         -6.1927e-01, -5.9280e-01, -4.1716e-01, -6.6201e-01, -9.2625e-01,
         -1.0919e+00, -1.1891e+00, -1.2612e+00, -1.3198e+00, -1.3056e+00,
         -1.2534e+00, -1.1011e+00, -7.9494e-01, -4.9740e-01],
        [-4.2309e-01, -4.2305e-01, -5.1036e-01, -5.4998e-01, -4.1993e-01,
         -2.1216e-01, -1.3223e-01, -1.9946e-01, -1.9763e-01, -2.5982e-01,
         -2.9762e-01, -4.1522e-01, -9.9264e-01, -8.6405e-01, -5.3401e-01,
         -2.0094e-01,  8.4615e-02,  3.7482e-01,  4.6478e-01,  4.1044e-01,
          2.4881e-01, -9.8644e-02, -5.5783e-01, -8.9267e-01],
        [ 4.5410e-01,  3.0860e-01,  1.9488e-01, -1.7502e-01, -3.0710e-01,
         -4.8888e-01, -5.9850e-01, -6.4025e-01, -3.2703e-01,  1.4273e-01,
          5.2416e-01,  8.0841e-01,  6.3585e-01,  6.6924e-01,  6.8927e-01,
          6.9006e-01,  7.4137e-01,  8.0048e-01,  8.1178e-01,  8.3271e-01,
          8.0155e-01,  7.9376e-01,  7.7519e-01,  6.7587e-01],
        [-5.9633e-01, -6.1760e-01, -6.4714e-01, -6.7335e-01, -7.0715e-01,
         -6.8665e-01, -7.0476e-01, -7.2081e-01, -7.5958e-01, -7.4423e-01,
         -6.8400e-01, -6.3167e-01, -1.1212e+00, -1.3844e+00, -1.6838e+00,
         -1.8249e+00, -1.9056e+00, -1.9448e+00, -1.9456e+00, -1.9390e+00,
         -1.9448e+00, -1.8370e+00, -1.5410e+00, -1.1876e+00],
        [ 1.0170e-01,  8.1473e-02, -4.8489e-02, -4.2908e-02,  2.5707e-01,
          3.0709e-01,  2.4295e-01,  1.0477e-02,  4.0363e-02,  2.4799e-01,
          2.5939e-01,  1.5286e-01,  2.3179e-01,  2.6240e-01,  3.9510e-01,
          5.2743e-01,  6.0427e-01,  6.2635e-01,  6.6100e-01,  6.4849e-01,
          5.5011e-01,  4.5636e-01,  3.4724e-01,  2.3354e-01],
        [-2.3971e-01, -2.8808e-01, -3.4782e-01, -2.7313e-01, -3.2015e-01,
         -1.1948e-02,  2.4801e-01,  4.3267e-01,  4.8739e-01,  6.9626e-02,
         -8.4820e-02, -1.6254e-01, -3.2226e-01, -1.0570e-01, -6.3327e-02,
          1.3118e-01,  2.8584e-01,  3.9202e-01,  4.0282e-01,  3.8146e-01,
          3.0733e-01,  1.2874e-01, -1.0674e-01, -2.8721e-01],
        [ 3.6198e-01,  3.3932e-01,  1.0695e-01, -2.0805e-01, -4.3299e-01,
         -5.4992e-01, -5.4211e-01, -6.2398e-01, -5.7769e-01, -4.4306e-01,
         -1.3385e-01,  1.9439e-01,  1.8587e-01,  2.7347e-01,  3.5342e-01,
          3.6710e-01,  4.2958e-01,  5.1241e-01,  6.2795e-01,  6.3607e-01,
          5.9346e-01,  5.0037e-01,  3.3567e-01,  1.6139e-01]]) tensor([[0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0.]])
tensor([[-3.8590e-01, -3.7000e-01, -3.1673e-01, -2.6730e-01, -2.9777e-01,
         -2.8297e-01, -2.3055e-01, -2.2967e-01, -3.6685e-01, -4.4403e-01,
         -4.7414e-01, -3.8518e-01, -6.0082e-01, -6.9522e-01, -8.8947e-01,
         -1.0874e+00, -1.2466e+00, -1.2612e+00, -1.2578e+00, -1.2166e+00,
         -1.1797e+00, -1.1500e+00, -9.7711e-01, -7.0131e-01],
        [ 2.0480e-01,  1.5780e-01,  6.5202e-02,  4.5251e-01,  4.6316e-01,
          4.8126e-01,  2.4873e-01,  3.2964e-01,  5.7426e-01,  4.6145e-01,
          5.9575e-01,  3.3309e-01,  1.2022e+00,  1.1481e+00,  9.6629e-01,
          7.2212e-01,  5.0255e-01,  3.2753e-01,  2.6030e-01,  2.9659e-01,
          4.3089e-01,  6.2751e-01,  8.8507e-01,  1.0806e+00],
        [ 1.6338e+00,  1.5262e+00,  2.1738e+00,  2.2613e+00,  1.8032e+00,
          3.6813e-01,  1.4825e-01,  8.1304e-01,  1.4430e+00,  2.7480e+00,
          3.2768e+00,  2.5321e+00,  1.4593e+00,  1.4027e+00,  1.2458e+00,
          1.0817e+00,  9.3818e-01,  8.0908e-01,  7.3536e-01,  7.6648e-01,
          8.7308e-01,  1.0480e+00,  1.2812e+00,  1.4256e+00],
        [-2.0337e-01, -2.5922e-01, -2.8742e-01, -1.6725e-01, -2.1750e-02,
          1.6059e-01,  2.4584e-01,  1.1196e-01, -3.7459e-02, -2.7842e-02,
         -2.1078e-02, -1.4222e-01, -2.1513e-01, -1.4445e-01,  8.6212e-02,
          3.1900e-01,  4.6496e-01,  5.0381e-01,  5.2055e-01,  4.7875e-01,
          3.8103e-01,  2.4365e-01,  6.0969e-02, -1.8683e-01],
        [ 3.4097e-02,  6.7510e-02,  1.3981e-01,  2.4463e-01,  4.8088e-01,
          4.5359e-01,  9.6923e-02, -6.8540e-02,  1.1366e-01,  1.4760e-01,
          1.2700e-01,  2.3326e-01,  3.3281e-01,  4.3953e-01,  5.7406e-01,
          6.4654e-01,  6.9715e-01,  7.1234e-01,  7.1677e-01,  7.4371e-01,
          6.6282e-01,  5.9817e-01,  5.1784e-01,  3.4020e-01],
        [-5.9802e-01, -6.2505e-01, -6.6136e-01, -6.9083e-01, -7.0155e-01,
         -6.1666e-01, -6.2669e-01, -7.0842e-01, -7.4691e-01, -7.5885e-01,
         -6.9184e-01, -6.3167e-01, -1.5697e-01,  1.3508e-01,  3.5587e-01,
          4.9766e-01,  5.4236e-01,  5.8765e-01,  6.1556e-01,  6.0709e-01,
          5.2626e-01,  3.5367e-01,  1.0145e-01, -1.6487e-01],
        [-5.6083e-01, -5.7944e-01, -6.0540e-01, -6.2672e-01, -6.4840e-01,
         -6.5410e-01, -6.6934e-01, -7.0145e-01, -7.1886e-01, -6.9257e-01,
         -6.5163e-01, -6.0958e-01, -1.0079e+00, -1.3567e+00, -1.6764e+00,
         -1.8134e+00, -1.8746e+00, -1.9319e+00, -1.9621e+00, -1.9286e+00,
         -1.9188e+00, -1.7954e+00, -1.4600e+00, -1.0432e+00],
        [-4.0365e-01, -4.9008e-01, -5.1036e-01, -4.4410e-01, -3.8636e-01,
         -2.8225e-02,  4.4152e-02,  4.6886e-02, -2.2749e-01, -3.9432e-01,
         -4.1138e-01, -3.7104e-01, -1.1947e+00, -1.0052e+00, -5.7323e-01,
         -2.5591e-01, -6.1332e-02,  2.5873e-01,  3.8423e-01,  3.1522e-01,
          1.1441e-01, -2.6490e-01, -8.5856e-01, -1.1750e+00],
        [-5.7097e-01, -5.3569e-01, -4.7483e-01, -4.6838e-01, -5.6447e-01,
         -6.2642e-01, -5.7898e-01, -5.5116e-01, -6.5099e-01, -6.2337e-01,
         -6.3398e-01, -6.0428e-01, -9.4366e-01, -1.2183e+00, -1.4852e+00,
         -1.6073e+00, -1.6734e+00, -1.7255e+00, -1.7349e+00, -1.7403e+00,
         -1.7107e+00, -1.6096e+00, -1.3472e+00, -1.0150e+00],
        [-5.1182e-01, -5.1521e-01, -4.4907e-01,  1.2515e-01,  1.0395e+00,
         -2.1949e-01, -2.0958e-01,  4.3035e-01,  8.1587e-01,  2.5668e+00,
          1.3685e+00, -9.0094e-02,  1.5174e+00,  1.5245e+00,  1.4419e+00,
          1.3131e+00,  1.1460e+00,  9.5527e-01,  8.6548e-01,  8.8239e-01,
          9.9013e-01,  1.1630e+00,  1.3766e+00,  1.4821e+00],
        [-3.2590e-01, -3.8210e-01, -3.5670e-01, -2.8964e-01,  1.3686e-02,
          4.3080e-01,  3.5500e-01,  7.1676e-02,  1.5529e-01,  4.9157e-02,
         -2.2309e-01, -2.9683e-01, -5.6103e-01, -3.6310e-01,  2.8623e-03,
          2.1135e-01,  3.6324e-01,  5.1456e-01,  5.9697e-01,  5.9674e-01,
          4.8074e-01,  2.9499e-01, -2.5779e-02, -3.9074e-01],
        [-5.8957e-01, -5.9899e-01, -6.2227e-01, -5.9175e-01, -5.2904e-01,
         -2.5530e-01, -2.2621e-01, -5.3567e-01, -6.3470e-01, -7.2864e-01,
         -6.7125e-01, -6.2018e-01, -5.2736e-01, -3.0498e-01, -4.3716e-02,
          1.1057e-01,  1.8855e-01,  2.2004e-01,  2.6856e-01,  2.8210e-01,
          1.8378e-01, -1.0626e-02, -2.8891e-01, -5.1308e-01],
        [-5.8957e-01, -5.8502e-01, -6.1606e-01, -6.5489e-01, -6.1203e-01,
         -4.7260e-01,  1.5331e-01,  4.6521e-01, -2.6912e-01, -7.1402e-01,
         -6.5948e-01, -6.1665e-01,  1.1562e+00,  1.2671e+00,  1.3536e+00,
          1.3657e+00,  1.3252e+00,  1.1831e+00,  1.0349e+00,  1.0128e+00,
          1.1267e+00,  1.2901e+00,  1.3275e+00,  1.2060e+00],
        [ 4.4058e-01,  6.9026e-01,  2.7571e-01, -1.2645e-01, -6.5772e-01,
         -6.8828e-01, -7.1850e-01, -7.7039e-01, -7.4058e-01, -5.8633e-01,
         -3.7509e-01, -1.3692e-01,  1.4562e+00,  1.3363e+00,  1.1354e+00,
          8.9162e-01,  6.5071e-01,  4.2427e-01,  3.7597e-01,  4.8496e-01,
          7.0834e-01,  9.7958e-01,  1.2697e+00,  1.4601e+00],
        [-5.4055e-01, -5.6455e-01, -5.7697e-01, -5.9855e-01, -5.8685e-01,
         -5.2713e-01, -3.6717e-01, -3.1024e-01, -4.3653e-01, -4.6352e-01,
         -5.4965e-01, -5.3979e-01, -1.0110e+00, -9.3877e-01, -7.5709e-01,
         -5.1015e-01, -2.0507e-01,  3.5156e-02,  1.4257e-01,  1.1236e-01,
          3.8665e-03, -2.2823e-01, -5.8675e-01, -8.9267e-01],
        [-5.6590e-01, -5.6734e-01, -5.8763e-01, -6.0535e-01, -6.2788e-01,
         -5.9875e-01, -5.7392e-01, -5.9144e-01, -6.8357e-01, -7.0622e-01,
         -6.4085e-01, -5.6806e-01, -1.1334e+00, -1.2764e+00, -1.4778e+00,
         -1.6668e+00, -1.7707e+00, -1.7556e+00, -1.7453e+00, -1.7465e+00,
         -1.7129e+00, -1.6952e+00, -1.5034e+00, -1.2064e+00]]) tensor([[0., 0., 0., 0., 1.],
        [0., 0., 1., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 1.]])
tensor([[-4.8562e-01, -4.8915e-01, -4.1976e-01, -4.0913e-01, -3.7611e-01,
         -5.3852e-01, -5.4211e-01, -5.8679e-01, -5.3878e-01, -5.7464e-01,
         -5.5259e-01, -5.5127e-01, -4.3858e-01, -5.9281e-01, -7.4729e-01,
         -9.2702e-01, -1.0476e+00, -1.1386e+00, -1.1752e+00, -1.1462e+00,
         -1.1016e+00, -9.8861e-01, -7.6892e-01, -5.1936e-01],
        [ 3.1076e+00,  2.9429e+00,  2.7707e+00,  1.7853e+00,  6.9069e-01,
         -3.0667e-02, -4.0187e-01, -2.7228e-01,  4.4305e-01,  1.6876e+00,
          2.4737e+00,  2.8104e+00,  1.5572e+00,  1.4608e+00,  1.2948e+00,
          1.1252e+00,  9.6693e-01,  8.2843e-01,  7.7460e-01,  8.3892e-01,
          9.7496e-01,  1.1605e+00,  1.4027e+00,  1.5448e+00],
        [-4.9492e-01, -3.7186e-01, -2.0215e-01, -2.4885e-01, -2.4089e-01,
         -3.9691e-01, -4.0982e-01, -4.1559e-01, -4.6367e-01, -4.1089e-01,
         -4.8983e-01, -5.1240e-01, -2.8553e-01, -4.4613e-01, -6.5168e-01,
         -7.8272e-01, -9.0163e-01, -9.9244e-01, -1.0637e+00, -1.0592e+00,
         -1.0062e+00, -8.3702e-01, -6.0988e-01, -3.5309e-01],
        [-5.1266e-01, -5.4779e-01, -5.3967e-01, -4.8392e-01, -3.9476e-01,
         -4.2540e-01, -2.6091e-01, -1.0108e-01, -1.7410e-01, -1.8866e-01,
         -4.1039e-01, -4.7971e-01, -8.3959e-01, -7.8932e-01, -6.0755e-01,
         -3.4753e-01, -1.2104e-01,  1.0610e-01,  2.8922e-01,  2.3449e-01,
          1.1008e-01, -3.7521e-02, -3.2650e-01, -5.6955e-01],
        [-5.0168e-01, -4.8821e-01, -4.8638e-01, -4.7712e-01, -4.8148e-01,
         -4.6609e-01, -4.3007e-01, -4.6130e-01, -5.4783e-01, -6.1557e-01,
         -5.5455e-01, -4.7176e-01, -9.5591e-01, -1.0910e+00, -1.2817e+00,
         -1.4561e+00, -1.5783e+00, -1.5772e+00, -1.5614e+00, -1.5478e+00,
         -1.5178e+00, -1.4923e+00, -1.3183e+00, -1.0307e+00],
        [ 4.0012e-02, -6.0949e-02, -1.4086e-01, -5.0679e-02,  1.2559e-01,
          2.7291e-01,  1.3090e-01,  2.2816e-01,  2.2497e-01,  2.9185e-01,
          2.2212e-01,  1.0604e-01, -3.3451e-01, -1.7766e-01,  1.2053e-01,
          2.8235e-01,  4.0747e-01,  4.8661e-01,  5.3914e-01,  4.4149e-01,
          3.4418e-01,  1.9964e-01, -4.8912e-02, -2.6839e-01],
        [-3.0393e-01, -3.4672e-01, -3.5137e-01, -2.6924e-01, -1.3272e-01,
         -3.8806e-02,  1.0849e-01, -1.8706e-01, -2.5554e-01, -1.0192e-01,
         -8.2859e-02, -1.6077e-01, -4.6307e-01, -2.6069e-01,  5.9246e-02,
          3.8771e-01,  5.4678e-01,  6.3495e-01,  6.4241e-01,  5.8432e-01,
          4.5256e-01,  2.8277e-01, -7.7828e-02, -3.8446e-01],
        [-5.9126e-01, -6.0085e-01, -5.9296e-01, -4.4604e-01, -2.0079e-01,
          4.7312e-01,  8.9138e-01,  4.9077e-01, -5.6462e-02, -5.0738e-01,
         -6.2810e-01, -5.9280e-01, -4.2328e-01, -1.1678e-01,  2.3085e-01,
          4.9079e-01,  6.6177e-01,  7.3599e-01,  7.5601e-01,  7.2508e-01,
          6.0430e-01,  3.8301e-01,  6.0288e-03, -3.8760e-01],
        [-4.4928e-01, -5.1335e-01, -4.6151e-01, -4.1884e-01, -5.4116e-01,
         -5.9957e-01, -6.5778e-01, -7.1229e-01, -6.8085e-01, -6.0193e-01,
         -4.9963e-01, -4.5851e-01, -1.1105e-01,  1.8841e-02,  3.4362e-01,
          6.3279e-01,  7.9002e-01,  8.7142e-01,  8.7994e-01,  8.3892e-01,

## Building a pytorch model
The next step is build a class to encapsulate the architecture of the ML model that we are going to train. As with the dataset, we do this by


### Further reading
- [Classification tutorial - Pytorch docs](https://docs.pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html)
- [Classification tutorial - Machine Learning Mastery](https://machinelearningmastery.com/building-a-multiclass-classification-model-in-pytorch/ )

In [45]:
class ClimateZoneClassifier(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1 = torch.nn.Linear(24, 60)
        self.act1 = torch.nn.ReLU()
        self.layer2 = torch.nn.Linear(60, 60)
        self.act2 = torch.nn.ReLU()
        self.layer3 = torch.nn.Linear(60, 60)
        self.act3 = torch.nn.ReLU()
        self.output = torch.nn.Linear(60, 5)
        self.sigmoid = torch.nn.Sigmoid()
        self.lsm = torch.nn.Softmax(dim=-1)
 
    def forward(self, x):
        x = self.act1(self.layer1(x))
        x = self.act2(self.layer2(x))
        x = self.act3(self.layer3(x))
        # x = self.sigmoid(self.output(x))
        x = self.lsm(self.output(x))
        return x

In [46]:
cz_classifier = ClimateZoneClassifier().to(device)

In [47]:
cz_classifier

ClimateZoneClassifier(
  (layer1): Linear(in_features=24, out_features=60, bias=True)
  (act1): ReLU()
  (layer2): Linear(in_features=60, out_features=60, bias=True)
  (act2): ReLU()
  (layer3): Linear(in_features=60, out_features=60, bias=True)
  (act3): ReLU()
  (output): Linear(in_features=60, out_features=5, bias=True)
  (sigmoid): Sigmoid()
  (lsm): Softmax(dim=-1)
)

In [48]:
cz_classifier(cz_train_ds[:10][0].to(device))

tensor([[0.2137, 0.1695, 0.2110, 0.1922, 0.2135],
        [0.2135, 0.1696, 0.2111, 0.1921, 0.2136],
        [0.2134, 0.1695, 0.2114, 0.1920, 0.2138],
        [0.2132, 0.1695, 0.2115, 0.1919, 0.2139],
        [0.2131, 0.1694, 0.2118, 0.1918, 0.2139],
        [0.2127, 0.1695, 0.2119, 0.1917, 0.2142],
        [0.2125, 0.1694, 0.2120, 0.1915, 0.2145],
        [0.2122, 0.1695, 0.2120, 0.1913, 0.2149],
        [0.2122, 0.1695, 0.2121, 0.1913, 0.2150],
        [0.2120, 0.1695, 0.2121, 0.1911, 0.2152]], grad_fn=<SoftmaxBackward0>)

In [49]:
loss_fn = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(cz_classifier.parameters(), 
                             lr=training_params['learning_rate'])

### Experiment tracking with mlflow
In a project to develop a machine learning model, we are likely to train many different models as part of our experimentation, with different predictors, hyperparameters, architectures and other experimental choices that we vary to understand the problem and find the best solution. We will have a collection of different models, and to properly assess our experiments we need to know exactly which set of choices go with which model. Experiment tracking tools log all the elements of a training run together so they can be retrieved and analysed later. A common tool for this is **ML Flow**.

The way this typically work is as follows:
- Create an experiment
- For each training run, start a run within the experiment
    - log the hyperparameter for the training run e.g. number of epochs, batch size, learning rate etc.
    - log loss and other metrics during training (every epoch typically to show loss descreases with training).
    - log final metrics at the end of training
    - create plots and add to the run
    - log the model with the run
- After multiple runs, you can search through the experiment to find the best run, according to a metric of your choice.
- You can select models from some runs to register for subsequent use, as a way of "releasing" the model.
- You can load model from runs, or registered models, and use them for inference.

Behind the scenes, ML flow has two key components. 
- **database** - this stores this info about runs and experiments
- **artifact store** - This save all disk objects, such as model weights or plots, that don't get stored in the database. Each artifact path is stored in the database to associate it with the experiment.

Further Reading
- [ML Flow docs](https://mlflow.org/)
- [Tracking pytorch with mlflow](https://mlflow.org/docs/latest/ml/deep-learning/pytorch/)

### ML Flow server

In this tutorial, we're going to use the MLFlow server built into AzureML. We can then browse through our experiments from the **Jobs** functionality in the AzureML Studio GUI.

In [10]:
mlflow_server_uri = ml_client.workspaces.get(ml_client.workspace_name).mlflow_tracking_uri

In [12]:
print(f'connecting to mlflow server {mlflow_server_uri}')
mlflow.set_tracking_uri(mlflow_server_uri)

connecting to mlflow server azureml://southcentralus.api.azureml.ms/mlflow/v2.0/subscriptions/9734ed68-621d-47ed-babd-269110dbacb1/resourceGroups/1-da6c1ccf-playground-sandbox/providers/Microsoft.MachineLearningServices/workspaces/dscoptest1

In [13]:
mlflow.pytorch.autolog()

In [14]:
exp_name='climate_zones_torch_nn'

In [15]:
if mlflow.get_experiment_by_name(exp_name) is None:
    exp_id = mlflow.create_experiment(exp_name)
exp1 = mlflow.get_experiment_by_name(exp_name)
exp1

In [50]:
cz_signature = mlflow.models.infer_signature(cz_train_ds[:5][0].numpy(), cz_train_ds[:5][1].numpy())

## Run the training loop

In PyTorch, we will explicitly define a loop which cycles through the data and updates the weights of the network to produce better predictions, which is to say predictions that are closer to the target data provided. Key steps in the training loop are:

- Iterate through the full data set for the number of epochs specified. An epoch is one full pass through the data.
- In each epoch, divide the dataset into minibatches. This is a set of data on which gradient descent is done.
- For each minibatch, do the follwing steps:
  -  Do a forward pass, or inference step to make predictions with the current weights. At the start of the process these will essentially be nonsense, but as we refine the weights the performance improves.
  -  Calculate the loss or error of the predictions.
  -  Do back propogation to update the weights towards weights that would produce correct predictions. This is done by calculating the gradient in the weights and moving the weights. The amount one updates the weight is based on the learning rate.
  -  Update the weights based on the calculated gradients.

### Further reading
- [Training a model - pytorch docs](https://docs.pytorch.org/tutorials/beginner/introyt/trainingyt.html)
- [ Introduction to NNs - Kaggle](https://www.kaggle.com/code/carlosaguayo/introduction-to-neural-networks/notebook)
- [Tutorial on NNs for weather](https://github.com/MetOffice/ml_weather_tutorial/blob/main/03_algorithm_selection.ipynb)

In [51]:
def get_classification_metrics(model, cz_data, set_label, target_encoder):
    class_labels = target_encoder.classes_
    return pandas.DataFrame({
        'climate_group': class_labels,
        f'precision_{set_label}': sklearn.metrics.precision_score(
            target_encoder.inverse_transform(model(cz_data._X.to(device)).to('cpu').detach().numpy()),
            target_encoder.inverse_transform(cz_data._y.numpy()),
            average=None,
            labels=class_labels,
        ),
        f'recall_{set_label}': sklearn.metrics.recall_score(
            target_encoder.inverse_transform(model(cz_data._X.to(device)).to('cpu').detach().numpy()),
            target_encoder.inverse_transform(cz_data._y.numpy()),
            average=None,
            labels=class_labels,
        ),
    })

In [52]:
num_epochs = training_params['num_epochs']
# num_epochs = 1 # for debug

In [53]:
%%time
with mlflow.start_run(experiment_id=exp1.experiment_id) as current_run:
    print(current_run.info.run_id)
    mlflow.log_params(training_params)    
    mlflow.log_dict(cz_train_ds.stats_dict, 'stats.json')
    for epoch in range(num_epochs):
        print(f'epoch {epoch}')
        cz_classifier.train()
        epoch_loss_train = 0.0
        for batch_X, batch_y in cz_train_loader:
            optimizer.zero_grad()
            predictions = cz_classifier(batch_X.to(device))
            loss = loss_fn(predictions, batch_y.to(device))
            loss.backward()
            optimizer.step()
            epoch_loss_train += loss.to('cpu').item()

        #divide by number of batches
        epoch_loss_train /= len(cz_train_loader)
        
        epoch_loss_val = 0.0
        for X_val, y_val in cz_val_loader:
            epoch_loss_val += loss_fn(cz_classifier(X_val.to(device)), y_val.to(device)).item()    
        epoch_loss_val /= len(cz_val_loader)

        mlflow.log_metrics(
            { 'cross_entropy_train': epoch_loss_train,
            'cross_entropy_val': epoch_loss_val, },
            step=epoch,
        )
            
    metrics_df = get_classification_metrics(cz_classifier,
                                               cz_train_ds, 
                                               'train', 
                                               target_encoder=cz_train_ds.target_encoder)
    
    metrics_df = metrics_df.merge( get_classification_metrics(cz_classifier,
                                               cz_val_ds, 
                                               'val', 
                                               target_encoder=cz_train_ds.target_encoder), on='climate_group')
    mlflow.log_table(metrics_df, 'metrics.csv')
        
    torch.save(cz_classifier,'cz_model.pth')
    mlflow.log_artifact('cz_model.pth')
    
    # mlflow.pytorch.log_model(cz_classifier,
    #                      name='climate_zones_classifier_torch', 
    #                      # signature=cz_signature, 
    #                      # input_example = cz_train_ds[:5][0].numpy(),
    #                      # export_model=True,
    #                     )

573b9d54-7191-40ec-94d6-8ecabe34a24a
epoch 0

Exception ignored in: <function PeriodicExportingMetricReader.__init__.<locals>.<lambda> at 0x740c27d22d40>
 Traceback (most recent call last):
  File "/anaconda/envs/dscop_pytorch/lib/python3.12/site-packages/opentelemetry/sdk/metrics/_internal/export/__init__.py", line 535, in <lambda>
    after_in_child=lambda: weak_at_fork()()  # pylint: disable=unnecessary-lambda
                          ^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
Exception ignored in: <function PeriodicExportingMetricReader.__init__.<locals>.<lambda> at 0x740c27d22d40>
Traceback (most recent call last):
  File "/anaconda/envs/dscop_pytorch/lib/python3.12/site-packages/opentelemetry/sdk/metrics/_internal/export/__init__.py", line 535, in <lambda>
    after_in_child=lambda: weak_at_fork()()  # pylint: disable=unnecessary-lambda
                           ^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable

epoch 1

Exception ignored in: <function PeriodicExportingMetricReader.__init__.<locals>.<lambda> at 0x740c27d22d40>
 Traceback (most recent call last):
  File "/anaconda/envs/dscop_pytorch/lib/python3.12/site-packages/opentelemetry/sdk/metrics/_internal/export/__init__.py", line 535, in <lambda>
    after_in_child=lambda: weak_at_fork()()  # pylint: disable=unnecessary-lambda
                          ^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
Exception ignored in: <function PeriodicExportingMetricReader.__init__.<locals>.<lambda> at 0x740c27d22d40>
Traceback (most recent call last):
  File "/anaconda/envs/dscop_pytorch/lib/python3.12/site-packages/opentelemetry/sdk/metrics/_internal/export/__init__.py", line 535, in <lambda>
    after_in_child=lambda: weak_at_fork()()  # pylint: disable=unnecessary-lambda
                           ^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable

🏃 View run gray_mango_85c2h0fy at: https://southcentralus.api.azureml.ms/mlflow/v2.0/subscriptions/9734ed68-621d-47ed-babd-269110dbacb1/resourceGroups/1-da6c1ccf-playground-sandbox/providers/Microsoft.MachineLearningServices/workspaces/dscoptest1/#/experiments/c7fb9cfc-27ad-4472-aaf7-51d8121a6f11/runs/573b9d54-7191-40ec-94d6-8ecabe34a24a
🧪 View experiment at: https://southcentralus.api.azureml.ms/mlflow/v2.0/subscriptions/9734ed68-621d-47ed-babd-269110dbacb1/resourceGroups/1-da6c1ccf-playground-sandbox/providers/Microsoft.MachineLearningServices/workspaces/dscoptest1/#/experiments/c7fb9cfc-27ad-4472-aaf7-51d8121a6f11
CPU times: user 6min 55s, sys: 41.9 s, total: 7min 36s
Wall time: 2min 46s

In [54]:
torch.save(cz_classifier,'cz_model.pth')
mlflow.log_artifact('cz_model.pth')

### Load model and do inference

After the run, we can look at the experiment to see details of the run. On some systems we can use a GUI to inspect results, by going to the same URI at the server, but on many systems the GUI is not available, so we can access the results through the python interface. Here we search through runs in an experiment, and look up a metric for the recent run.

In [55]:
mlflow.search_runs(exp1.experiment_id)

,run_id,experiment_id,status,artifact_uri,start_time,end_time,metrics.cross_entropy_train,metrics.cross_entropy_val,params.criterion,params.optimizer,params.learning_rate,params.loss,params.num_epochs,params.batch_size,tags.mlflow.rootRunId,tags.mlflow.loggedArtifacts,tags.mlflow.runName,tags.mlflow.user
0,573b9d54-7191-40ec-94d6-8ecabe34a24a,c7fb9cfc-27ad-4472-aaf7-51d8121a6f11,FINISHED,,2026-08-25 21:09:26.143000+00:00,2026-08-25 21:12:12.500000+00:00,0.941622,0.951538,CrossEntropyLoss,Adam,0.001,CrossEntropyLoss,2,16,573b9d54-7191-40ec-94d6-8ecabe34a24a,"[{""path"": ""metrics.json"", ""type"": ""table""}]",gray_mango_85c2h0fy,Cloud Student c3fd45b1

In [56]:
model_inference = torch.load('cz_model.pth', weights_only=False)

In [57]:
model_inference

ClimateZoneClassifier(
  (layer1): Linear(in_features=24, out_features=60, bias=True)
  (act1): ReLU()
  (layer2): Linear(in_features=60, out_features=60, bias=True)
  (act2): ReLU()
  (layer3): Linear(in_features=60, out_features=60, bias=True)
  (act3): ReLU()
  (output): Linear(in_features=60, out_features=5, bias=True)
  (sigmoid): Sigmoid()
  (lsm): Softmax(dim=-1)
)

In [58]:
cz_train_ds.target_encoder.inverse_transform(
    model_inference(cz_val_ds._X.to(device)).to('cpu').detach().numpy()
)

array(['A', 'B', 'E', ..., 'E', 'C', 'D'], shape=(40644,), dtype='<U1')

### Evaluation

We will go into more details on evaluating the performance of a machine learning model in a separate notebook.

In [ ]:
# load metrics from mlflow to see training

In [59]:
current_run.info.run_id

'573b9d54-7191-40ec-94d6-8ecabe34a24a'

In [60]:
metrics_path = pathlib.Path(mlflow.artifacts.download_artifacts(f'runs:/{current_run.info.run_id}/metrics.json'))
metrics_path

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00,  3.51it/s]

PosixPath('/tmp/tmpu3dawl33/metrics.json')

In [61]:
with open(metrics_path) as metrics_file:
    metrics_mlflow_dict = json.load(metrics_file)
metrics_mlflow_dict

{'columns': ['climate_group',
  'precision_train',
  'recall_train',
  'precision_val',
  'recall_val'],
 'data': [['A', 0.9466113485, 0.9473644953, 0.9470368183, 0.9429523623],
  ['B', 0.9436749465, 0.9737244119, 0.9443430657, 0.9733978235],
  ['C', 0.8587626596, 0.8432905737, 0.847275975, 0.8417627921],
  ['D', 0.9441472897, 0.9640816223, 0.9437305296, 0.9613248711],
  ['E', 0.991855079, 0.9662484064, 0.9910952181, 0.9658353263]]}

In [62]:
pandas.DataFrame(metrics_mlflow_dict['data'],columns=metrics_mlflow_dict['columns'])

  climate_group  precision_train  recall_train  precision_val  recall_val
0             A         0.946611      0.947364       0.947037    0.942952
1             B         0.943675      0.973724       0.944343    0.973398
2             C         0.858763      0.843291       0.847276    0.841763
3             D         0.944147      0.964082       0.943731    0.961325
4             E         0.991855      0.966248       0.991095    0.965835

In [67]:
mlflow.search_runs(exp1.experiment_id,
                   max_results=5,
                  )

,run_id,experiment_id,status,artifact_uri,start_time,end_time,metrics.cross_entropy_train,metrics.cross_entropy_val,params.criterion,params.optimizer,params.learning_rate,params.loss,params.num_epochs,params.batch_size,tags.mlflow.rootRunId,tags.mlflow.loggedArtifacts,tags.mlflow.runName,tags.mlflow.user
0,573b9d54-7191-40ec-94d6-8ecabe34a24a,c7fb9cfc-27ad-4472-aaf7-51d8121a6f11,FINISHED,,2026-08-25 21:09:26.143000+00:00,2026-08-25 21:12:12.500000+00:00,0.941622,0.951538,CrossEntropyLoss,Adam,0.001,CrossEntropyLoss,2,16,573b9d54-7191-40ec-94d6-8ecabe34a24a,"[{""path"": ""metrics.json"", ""type"": ""table""}]",gray_mango_85c2h0fy,Cloud Student c3fd45b1

In [ ]:
# calculate metrics from predictions on test vset

In [69]:
test_metrics_df = get_classification_metrics(model_inference,
                                             cz_test_ds, 
                                             'test', 
                                             target_encoder=cz_train_ds.target_encoder)
test_metrics_df

  climate_group  precision_test  recall_test
0             A        0.945941     0.949702
1             B        0.944143     0.975030
2             C        0.855220     0.841873
3             D        0.944782     0.961749
4             E        0.991991     0.966046

# Exercises

Once you have worked through the tutorial above, you can test your knowledge by adapting the code in the tutorial to experiment with different options for training the model and comparing results.

### Varying model architecture
Try to change the model architecture e.g. add more layers

In [ ]:
# insert code here

### Next steps or potential follow on material

Links from notebook
- [PyTorch docs](https://pytorch.org/)

Additional excercises in this tutorial material includes:
- Training a CNN autoencoder on CMIP6 data
- Training a RNN on Jena weather dataset for time series prediction.

### Data statement
This data used in this notebook is derived from the Koppen-Geiger Climate Cliassfication dataset created by GloH2O.

###     References
- [Climate Zones Dataset](https://www.gloh2o.org/koppen/#:~:text=The%20K%C3%B6ppen%2DGeiger%20climate%20classification%20maps%20are%20high%2Dresolution,Climate%20Sensitivity%20(ECS)%2C%20and%20historical%20warming%20trend)